# Generated by Django 3.2.9 on 2021-12-05 17:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCategoryMixin',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.post')),
            ],
            bases=('main_app.post',),
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_data']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='Текст коментаря'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='main_app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Стаття'),
        ),
        migrations.CreateModel(
            name='AllRestaurant',
            fields=[
                ('modelcategorymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.modelcategorymixin')),
            ],
            bases=('main_app.modelcategorymixin', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='MainView',
            fields=[
                ('modelcategorymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.modelcategorymixin')),
            ],
            bases=('main_app.modelcategorymixin', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('modelcategorymixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_app.modelcategorymixin')),
            ],
            bases=('main_app.modelcategorymixin', django.views.generic.list.ListView),
        ),
    ]
