# Generated by Django 3.2.9 on 2021-12-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211205_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=150, verbose_name='Текст коментаря'),
        ),
    ]
