# Generated by Django 3.2.8 on 2021-12-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_replaycoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaycoment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main_app.comment'),
        ),
    ]
